# import

In [2]:
import numpy as np
import torch

In [9]:
t1 = np.array([0.,1.,2.,3.,4.,5.,6.,7.,8.,9.,10])
t2 = np.array([[0.,1.,2.,3.,4.,5.,6.,7.,8.,9.,10],[0.,1.,2.,3.,4.,5.,6.,7.,8.,9.,10]])
print(t1)
print(t2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [11]:
print('Rank of t : ', t1.ndim)
print('Shape of t: ', t1.shape)

print('Rank of t : ', t2.ndim)
print('Shape of t: ', t2.shape)

Rank of t :  1
Shape of t:  (11,)
Rank of t :  2
Shape of t:  (2, 11)


In [13]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])  # Element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])     # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:])           # Slicing

t[0] t[1] t[-1] =  0.0 1.0 10.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5. 6. 7. 8. 9.]
t[:2] t[3:] =  [0. 1.] [ 3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [24]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[2]) #Element
print(t[2:5], t[4:-1])  #Slicing
print(t[:2], t[3:])     #Slicing

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([1., 2., 3.]) tensor([4., 5., 6.]) tensor([7., 8., 9.])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]) tensor([], size=(0, 3))
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[10., 11., 12.]])


In [26]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.],
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [28]:
print(t.dim())   # rank
print(t.size())  # shape
print(t[:,1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# PyTorch Tensor Operation(addition)

In [34]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[4., 5.]])


In [44]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

# Multiplicatioin vs Matrix Multiplication

In [45]:
print('-----------------------')
print("Mul vs Matmul")
print("=======================")
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print("Shape of Matrix 1:", m1.shape)  # 2x2
print("Shape of Matrix 2:", m2.shape)  # 2x1
print(m1.matmul(m2))  # 2x1

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)  # 2x2
print('Shape of Matrix 2: ', m2.shape)  # 2x1
print(m1 * m2)
print(m1.mul(m2))

-----------------------
Mul vs Matmul
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [47]:
t = torch.FloatTensor([[1,2]])
print(t.mean())

tensor(1.5000)


In [49]:
#Can't use mean() on integers
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exe:
    print(exe)

Can only calculate the mean of floating types. Got Long instead.


In [51]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [54]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [56]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [58]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [60]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [62]:
print(t.max())  # Returns one value: max

tensor(4.)


In [64]:
print(t.max(dim=0))  # Returns two values: max and argmax
print("max : ", t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max :  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [66]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# View(Reshape)

In [68]:
t = np.array([ [[0,1,2],[3,4,5]], [[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [70]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze

In [72]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [74]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# Unsqueeze

In [76]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [78]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [80]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [82]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [84]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [86]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [88]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [90]:
bt = torch.ByteTensor([True,False, False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [94]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate

In [96]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stack

In [98]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [103]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [105]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [107]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [109]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [111]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# Gradient Descent

In [4]:
import torch
import torch.optim as optim

#데이터 정의
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
#Hypothesis 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
#Optimizer 정의
optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1000
for epoch in range(1, nb_epochs+1):
    hypothesis = x_train*W + b #hypothesis 예측
    cost = torch.mean((hypothesis - y_train)**2)
    
    #Optimizer 학습
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    